[
  {
    "PO": "4200234274",
    "Orphan Site": "D1D",
    "Entity Code": "DEA482",
    "CAT": "MT",
    "WBS": "FS00054.ET.0675",
    "STD - Ship Date": "44683",
    "FA": "ET",
    "CEID": "DEAfs",
    "Process": "1276",
    "Suppler": "APPLIED MATERIALS INC",
    "SIRFIS Description": "DEA TOOL",
    "Material": "700027559",
    "PO$": "3260811.35",
    "Ueid": "231166",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "2/2/2022",
    "Dispo Date": "4/18/2022",
    "Closed Date": "4/20/2022",
    "Owner": "Ryan",
    "Comments": "",
    "Internal/Cross site": "Internal",
    "Proposed Site": "D1D",
    "Proposed Entity": "DEA482",
    "Proposed CEID": "DEAfs",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "4/20/2022",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200235348",
    "Orphan Site": "F24",
    "Entity Code": "CDO439",
    "CAT": "CK",
    "WBS": "FS00022.TF.0738",
    "STD - Ship Date": "22 Jun 2022",
    "FA": "TF",
    "CEID": "CDOnc",
    "Process": "1274",
    "Suppler": "ASM AMERICA INC",
    "SIRFIS Description": "CDOcu/1274 TO CDOnc/1274",
    "Material": "750017393",
    "PO$": "$373,756.27",
    "Ueid": "197341",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "Stranded ",
    "Execution Status": "",
    "Orphaned Date": "4/22/2022",
    "Dispo Date": "4/21/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/4/22 receive CK.",
    "Internal/Cross Site": "Cross Site",
    "Proposed Site": "",
    "Proposed Entity": "",
    "Proposed CEID": "",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "1274 Unique",
    "On Hold Date (mm/ dd / yy)": "4/20/2022",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200246178",
    "Orphan Site": "D1D",
    "Entity Code": "VSO406",
    "CAT": "MT",
    "WBS": "FS00080.DI.0036",
    "STD - Ship Date": "5 Sep 2022",
    "FA": "DI",
    "CEID": "VFOae",
    "Process": "1278",
    "Suppler": "ASM AMERICA INC",
    "SIRFIS Description": "FURNACE",
    "Material": "700029480",
    "PO$": "$1,515,285.97",
    "Ueid": "237475",
    "NeedId": "",
    "Status": "Swap Cost Assesment",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "2/1/2022",
    "Dispo Date": "2/1/2022",
    "Closed Date": "2/14/2022",
    "Owner": "Ryan",
    "Comments": "2/8 - Working supplier alignment from VFO456 to VSO406",
    "Internal / Cross site": "Internal",
    "Proposed Site": "D1D",
    "Proposed Entity": "VSO406",
    "Proposed CEID": "",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200228772",
    "Orphan Site": "F32",
    "Entity Code": "CDT472",
    "CAT": "MT",
    "WBS": "FS00022.TF.0717",
    "STD - Ship Date": "18 Jan 2022",
    "FA": "TF",
    "CEID": "CDTsn",
    "Process": "1274",
    "Suppler": "ASM AMERICA INC",
    "SIRFIS Description": "2DC1, 2LP ALD TOOL",
    "Material": "700019169",
    "PO$": "$2,288,625.00",
    "Ueid": "230292",
    "NeedId": "255094",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "8/4/2021",
    "Dispo Date": "4/30/2022",
    "Closed Date": "",
    "Owner": "Augustin",
    "Comments": "AJ: Updated recommendation 1/31/2022",
    "Internal/Cross Site": "",
    "Proposed Site": "",
    "Proposed Entity": "",
    "Proposed CEID": "",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "D1D",
    "RTD": "",
    "Budget approved": "",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": "",
    "Next Trigger (by line)2": ""
  },
  {
    "PO": "4200230627",
    "Orphan Site": "F12",
    "Entity Code": "GTO440",
    "CAT": "MT",
    "WBS": "FS00022.ET.1108",
    "STD - Ship Date": "7 May 2022",
    "FA": "ET",
    "CEID": "GTOvj",
    "Process": "1274",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700023605",
    "PO$": "$7,297,415.22",
    "Ueid": "231011",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "2/4/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/4/22 jseymour -- receive tool and allocate as reuse later. 2 / 3 / 22 - will orphan DS1 chambers(not used in 1276 +); minimal chamber level hardware(lafranze)",
    "Internal/Cross Site": "Cross Site",
    "Proposed Site": "",
    "Proposed Entity": "",
    "Proposed CEID": "",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "1274 Unique",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200231481",
    "Orphan Site": "F24",
    "Entity Code": "GTO450",
    "CAT": "MT",
    "WBS": "FS00022.ET.1092",
    "STD - Ship Date": "25 Apr 2022",
    "FA": "ET",
    "CEID": "GTOti",
    "Process": "1274",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700028274",
    "PO$": "$6,497,770.64",
    "Ueid": "246100",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/30/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/4/22 jseymour -- receive tool and allocate as reuse later. 2 / 3 / 22 - will orphan DS1 chambers(not used in 1276 +); minimal chamber level hardware(lafranze)",
    "Internal/Cross Site": "Cross Site",
    "Proposed Site": "F32",
    "Proposed Entity": "GTO601",
    "Proposed CEID": "GTOcb",
    "Proposed Process": "1278",
    "Proposed WST": "ETS",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "1274 Unique",
    "On Hold Date (mm/ dd / yy)": "4/30/2022",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200233725",
    "Orphan Site": "F32",
    "Entity Code": "GTT550",
    "CAT": "MT",
    "WBS": "FS00022.ET.1131",
    "STD - Ship Date": "5 Apr 2022",
    "FA": "ET",
    "CEID": "GTTvs",
    "Process": "1274",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700023344",
    "PO$": "$8,944,439.63",
    "Ueid": "232764",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/25/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/4/22  Near term Tender Date.Proposed Plan will not be funded until March.Receive Tool and Allocate. 2/3/22 - best reuse path without an expensive ck with a long work duration(lafranze)",
    "Internal/Cross Site": "Cross Site",
    "Proposed Site": "F32",
    "Proposed Entity": "GTT510",
    "Proposed CEID": "GTTvs",
    "Proposed Process": "1278",
    "Proposed WST": "ETS",
    "Orphan Driver": "LRP Change ",
    "RTD": "6/22/2023",
    "Budget approved": "Config Mismatch",
    "Config Type": "Fungible",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200235253",
    "Orphan Site": "F68",
    "Entity Code": "GTT594",
    "CAT": "MT",
    "WBS": "FS00022.ET.1118",
    "STD - Ship Date": "12 Apr 2022",
    "FA": "ET",
    "CEID": "GTTtr",
    "Process": "1274",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700025235",
    "PO$": "$8,125,264.84",
    "Ueid": "231176",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "1/28/2022",
    "Dispo Date": "4/30/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/4/22 Near term Tender Date.Proposed plan will not be funded until March and will need to be upgraded.Allocate post GR. 2/3/22 - Add APTC2, iM2, P9H, C5K(lafranze)",
    "Internal/Cross Site": "Cross Site",
    "Proposed Site": "F32",
    "Proposed Entity": "GTT534",
    "Proposed CEID": "GTTtg",
    "Proposed Process": "1278",
    "Proposed WST": "ETS",
    "Orphan Driver": "LRP Change ",
    "RTD": "7/1/2023",
    "Budget approved": "Config Mismatch",
    "Config Type": "Fungible",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger(by line)": ""
  },
  {
    "PO": "4200228710",
    "Orphan Site": "F11x ",
    "Entity Code": "GTT503",
    "CAT": "MT",
    "WBS": "FS00126.ET.0023",
    "STD - Ship Date": "10 Dec 2021",
    "FA": "ET",
    "CEID": "GTTcw",
    "Process": "1277",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700031204",
    "PO$": "$9,094,779.12",
    "Ueid": "225944",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "5/1/2022",
    "Closed Date": "2/23/2022",
    "Owner": "Ryan",
    "Comments": "Self-Swap GTTcw to GTTcc. Docking as Is. ",
    "Internal/Cross Site": "Internal",
    "Proposed Site": "D1D",
    "Proposed Entity": "GTT503",
    "Proposed CEID": "GTTgc",
    "Proposed Process": "1277",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200238408",
    "Orphan Site": "F12",
    "Entity Code": "PAT486",
    "CAT": "MT",
    "WBS": "FS00022.ET.1139",
    "STD - Ship Date": "18 Feb 2022",
    "FA": "ET",
    "CEID": "PATrt",
    "Process": "1274",
    "Suppler": "Lam Research Corporation",
    "SIRFIS Description": "ETCH",
    "Material": "700020564",
    "PO$": "$6,610,576.00",
    "Ueid": "234605",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/25/2022",
    "Closed Date": "",
    "Owner": "",
    "Comments": "2/3/22 jseymour. Near-term Tender Date. Receive PO and hold in Reserve.",
    "Internal/Cross Site": "",
    "Proposed Site": "",
    "Proposed Entity": "",
    "Proposed CEID": "",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "LRP Change ",
    "RTD": "",
    "Budget approved": "",
    "Config Type": "1274 Unique",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200231611",
    "Orphan Site": "F42",
    "Entity Code": "PLH478",
    "CAT": "MT",
    "WBS": "FS00054.PL.0107",
    "STD - Ship Date": "23 May 2022",
    "FA": "PL",
    "CEID": "PLHcn",
    "Process": "1276",
    "Suppler": "APPLIED MATERIALS INC",
    "SIRFIS Description": "POLISHER, CU",
    "Material": "700025333",
    "PO$": "$3,601,878.00",
    "Ueid": "230960",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "5/1/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/23/22 jseymour  Applied rejected swap due to F24 late RTD and F24 unwilling to dock early. Keep F24 PLH plan hold and revisit post next Cap Reset. AJ:  Updated recommendation 2/3/2022",
    "Internal/Cross Site": "",
    "Proposed Site": "F24",
    "Proposed Entity": "PLH858",
    "Proposed CEID": "PLHcn",
    "Proposed Process": "1276",
    "Proposed WST": "10500",
    "Orphan Driver": "LRP Change ",
    "RTD": "9/9/2023",
    "Budget approved": "",
    "Config Type": "Fungible",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200239974",
    "Orphan Site": "F68",
    "Entity Code": "PLH488",
    "CAT": "MT",
    "WBS": "FS00054.PL.0111",
    "STD - Ship Date": "10 May 2022",
    "FA": "PL",
    "CEID": "PLHch",
    "Process": "1276",
    "Suppler": "APPLIED MATERIALS INC",
    "SIRFIS Description": "POLISHER, CU",
    "Material": "700028142",
    "PO$": "$3,821,441.00",
    "Ueid": "231614",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "TMGSP Dispo Proposal",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "5/1/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/23/22 jseymour  Applied rejected swap due to F24 late RTD and F24 unwilling to dock early. Keep F24 PLH plan hold and revisit post next Cap Reset. AJ:  Updated recommendation 2/3/2022",
    "Internal/Cross Site": "",
    "Proposed Site": "F24",
    "Proposed Entity": "PLH860",
    "Proposed CEID": "PLHch",
    "Proposed Process": "1276",
    "Proposed WST": "",
    "Orphan Driver": "LRP Change ",
    "RTD": "9/30/2023",
    "Budget approved": "9/30/2023",
    "Config Type": "",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200235392",
    "Orphan Site": "F68",
    "Entity Code": "REX477",
    "CAT": "MT",
    "WBS": "FS00054.ET.0518",
    "STD - Ship Date": "18 Feb 2022",
    "FA": "ET",
    "CEID": "REXcv",
    "Process": "1276",
    "Suppler": "Hitachi High-Tech America, Inc.",
    "SIRFIS Description": "DRY ETCHER, CU",
    "Material": "700028760",
    "PO$": "$6,963,470.23",
    "Ueid": "227585",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "pending goods receipt",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/28/2022",
    "Closed Date": "2/23/2022",
    "Owner": "Ryan",
    "Comments": "",
    "Internal/Cross Site": "Internal",
    "Proposed Site": "D1D",
    "Proposed Entity": "REX477",
    "Proposed CEID": "REXcw",
    "Proposed Process": "1274",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200235251",
    "Orphan Site": "D1D",
    "Entity Code": "GTT554",
    "CAT": "MT",
    "WBS": "FS00054.ET.0548",
    "STD - Ship Date": "19 Feb 2022",
    "FA": "ET",
    "CEID": "GTTtq",
    "Process": "1276",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700025233",
    "PO$": "$9,414,477.25",
    "Ueid": "232126",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "10/19/2021",
    "Dispo Date": "4/28/2022",
    "Closed Date": "2/23/2022",
    "Owner": "Ryan",
    "Comments": "2/4/22  Allocate post goods receipt. 02/01/2022 Need to look at the full GTT list and come with proposal 1/21/21  Working supplier alignment.",
    "Internal/Cross Site": "Internal",
    "Proposed Site": "D1D",
    "Proposed Entity": "GTT554",
    "Proposed CEID": "GTTtc",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "Exact",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200233994",
    "Orphan Site": "D1D",
    "Entity Code": "GTT528",
    "CAT": "MT",
    "WBS": "FS00126.ET.0087",
    "STD - Ship Date": "21 Feb 2022",
    "FA": "ET",
    "CEID": "GTTtq",
    "Process": "1277",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700031236",
    "PO$": "$9,436,843.12",
    "Ueid": "231587",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/28/2022",
    "Closed Date": "2/23/2022",
    "Owner": "Ryan",
    "Comments": "Self-Swap GTTtq to GTTva. Docking as Is. ",
    "Internal/Cross Site": "Internal",
    "Proposed Site": "D1D",
    "Proposed Entity": "GTT528",
    "Proposed CEID": "GTTva",
    "Proposed Process": "1276",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200233989",
    "Orphan Site": "D1D",
    "Entity Code": "GTT505",
    "CAT": "MT",
    "WBS": "FS00126.ET.0024",
    "STD - Ship Date": "4 Mar 2022",
    "FA": "ET",
    "CEID": "GTTcw",
    "Process": "1277",
    "Suppler": "TOKYO ELECTRON LIMITED",
    "SIRFIS Description": "Multi-Chamber Etcher",
    "Material": "700031204",
    "PO$": "$9,111,374.89",
    "Ueid": "225945",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/28/2022",
    "Closed Date": "2/23/2022",
    "Owner": "Ryan",
    "Comments": "Self-Swap GTTcw to GTTcc. Docking as Is. ",
    "Internal/Cross Site": "Internal",
    "Proposed Site": "D1D",
    "Proposed Entity": "GTT505",
    "Proposed CEID": "GTTcc",
    "Proposed Process": "1277",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "Config Mismatch",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200245318",
    "Orphan Site": "D1D",
    "Entity Code": "CDT494",
    "CAT": "MT",
    "WBS": "FS00054.TF.0475",
    "STD - Ship Date": "17 May 2022",
    "FA": "TF",
    "CEID": "CDTsd",
    "Process": "1274",
    "Suppler": "ASM AMERICA INC",
    "SIRFIS Description": "1 DC1, 3DC2, 4LP ALD TOOL",
    "Material": "700029839",
    "PO$": "$3,863,387.00",
    "Ueid": "246432",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/30/2022",
    "Closed Date": "2/14/2022",
    "Owner": "Augustin",
    "Comments": "2/14/22 KH- Swap CDT494 -> CDT767 executed.F32 CDT767 received tool has been allocated to D1D CDT494. AJ: Updated recommendation 1 / 31 / 2022. CDT494 is still needed.Going to F32",
    "Internal/Cross Site": "Cross Site",
    "Proposed Site": "N/A",
    "Proposed Entity": "N/A",
    "Proposed CEID": "N/A",
    "Proposed Process": "N/A",
    "Proposed WST": "N/A",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "",
    "Config Type": "1274 Unique",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200222133",
    "Orphan Site": "D1D",
    "Entity Code": "RIO446",
    "CAT": "MT",
    "WBS": "FS00022.TF.0756",
    "STD - Ship Date": "11 Jul 2022",
    "FA": "TF",
    "CEID": "RIOnc",
    "Process": "1274",
    "Suppler": "APPLIED MATERIALS INC",
    "SIRFIS Description": "MCVD",
    "Material": "700018523",
    "PO$": "$3,251,586.00",
    "Ueid": "236227",
    "NeedId": "",
    "Status": "Closed",
    "Disposition Status": "Stranded ",
    "Execution Status": "cancel PO",
    "Orphaned Date": "",
    "Dispo Date": "2/2/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "Receive Tool. ",
    "Internal/Cross Site": "",
    "Proposed Site": "",
    "Proposed Entity": "",
    "Proposed CEID": "",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "",
    "Config Type": "",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200233053",
    "Orphan Site": "D1D",
    "Entity Code": "CSB421",
    "CAT": "CK",
    "WBS": "FS00022.TF.0748",
    "STD - Ship Date": "10 Aug 2022",
    "FA": "TF",
    "CEID": "CSBcp",
    "Process": "1274",
    "Suppler": "APPLIED MATERIALS INC",
    "SIRFIS Description": "CSBch/TD1276 TO CSBcp/1274",
    "Material": "750019210",
    "PO$": "$2,685,203.20",
    "Ueid": "113428",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "Stranded ",
    "Execution Status": "",
    "Orphaned Date": "1/20/2022",
    "Dispo Date": "4/30/2022",
    "Closed Date": "",
    "Owner": "Jeanine",
    "Comments": "2/4/22 receive CK.",
    "Internal/Cross Site": "Cross Site",
    "Proposed Site": "",
    "Proposed Entity": "",
    "Proposed CEID": "",
    "Proposed Process": "",
    "Proposed WST": "",
    "Orphan Driver": "",
    "RTD": "",
    "Budget approved": "",
    "Config Type": "1274 Unique",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200231861",
    "Orphan Site": "D1D",
    "Entity Code": "WDC416",
    "CAT": "MT",
    "WBS": "FS00126.TF.0080",
    "STD - Ship Date": "8 Feb 2022",
    "FA": "TF",
    "CEID": "WDCnl",
    "Process": "1277",
    "Suppler": "Lam Research Corporation",
    "SIRFIS Description": "Hard Mask Tool on HLi Platform",
    "Material": "700030828",
    "PO$": "$3,736,681.00",
    "Ueid": "231784",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "1/31/2022",
    "Dispo Date": "2/6/2022",
    "Closed Date": "",
    "Owner": "Michal - move to Receive WS",
    "Comments": "Near-term Tender Date. Use for D1D 1278 Ramp",
    "Internal/Cross Site": "Receive & Allocate",
    "Proposed Site": "D1D",
    "Proposed Entity": "WDC002",
    "Proposed CEID": "WDCnl",
    "Proposed Process": "1278",
    "Proposed WST": "3250",
    "Orphan Driver": "D1D",
    "RTD": "12/24/2023",
    "Budget approved": "Config Mismatch",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  },
  {
    "PO": "4200231860",
    "Orphan Site": "D1D",
    "Entity Code": "WDC418",
    "CAT": "MT",
    "WBS": "FS00126.TF.0081",
    "STD - Ship Date": "24 Mar 2022",
    "FA": "TF",
    "CEID": "WDCnl",
    "Process": "1277",
    "Suppler": "Lam Research Corporation",
    "SIRFIS Description": "Hard Mask Tool on HLi Platform",
    "Material": "700030828",
    "PO$": "$3,736,681.00",
    "Ueid": "226089",
    "NeedId": "",
    "Status": "Receive PO",
    "Disposition Status": "Dispo Execution",
    "Execution Status": "",
    "Orphaned Date": "1/31/2022",
    "Dispo Date": "4/26/2022",
    "Closed Date": "",
    "Owner": "Michal - move to Receive WS",
    "Comments": "Near-term Tender Date. Use for D1D 1278 Ramp",
    "Internal/Cross Site": "Receive & Allocate",
    "Proposed Site": "D1D",
    "Proposed Entity": "WDC003",
    "Proposed CEID": "WDCnl",
    "Proposed Process": "1278",
    "Proposed WST": "3250",
    "Orphan Driver": "D1D",
    "RTD": "12/24/2023",
    "Budget approved": "Config Mismatch",
    "Config Type": "Config Mismatch",
    "On Hold Date (mm/ dd / yy)": "4/16/2022",
    "Current Fee (by line)": "",
    "Next Fee (by line)": "",
    "Next Trigger (by line)": ""
  }
]